export const renderingsData = [
  {
    title: "Bistro Lounge",
    description: "Vibrant restaurant interior with green velvet booths and brick walls.",
    url: "/images/Posse/Render_bar_resto.jpg",
    tags: ["Interior", "Commercial"],
  },
  {
    title: "Workspace",
    description:"Open office for collaboration.",
    url: "/projects/Carramaldini/01-Office.png",
    tags: ["Interior", "Commercial"],
  },
  {
    title: "Madison Residence",
    description:"3D residential floorplan.",
    url: "/projects/Carramaldini/01-FP.jpg",
    tags: ["Floorplan", "Residential"],
  },
  {
    title: "Slatted Sideboard",
    description: "Minimalist wooden storage unit with unique vertical slat details.",
    url: "/images/Posse/Mueble_pajarito.jpg",
    tags: ["Furniture", "Interior"],
  },
  {
    title: "Open Interior",
    description:"Open interior with panoramic views.",
    url: "/projects/Noiseless/noiseless_04.jpg",
    tags: ["Interior", "Residential"],
  },
  {
    title: "Office Building",
    description:"Corporate facade for interior workspaces.",
    url: "/projects/Noiseless/noiseless_01.jpg",
    tags: ["Exterior", "Commercial"],
  },
  {
    title: "Wine Bar Interior",
    description: "Restaurant interior with wine display and warm lighting.",
    url: "/images/Posse/1810.jpg",
    tags: ["Interior", "Commercial"],
  },
  {
    title: "Modern Kitchen",
    description: "Sleek kitchen design with white cabinetry and integrated lighting.",
    url: "/images/Posse/Cocina.jpg",
    tags: ["Interior", "Residential"],
  },
  {
    title: "Minimalist Workspace",
    description: "Simple wooden desk setup with clean lines and natural light.",
    url: "/images/Posse/Escritorio.jpg",
    tags: ["Interior", "Furniture"],
  },
  {
    title: "Contemporary Living",
    description: "Spacious lounge featuring a drop ceiling and cozy seating.",
    url: "/images/Posse/living.jpg",
    tags: ["Interior", "Residential"],
  },
  {
    title: "Industrial Loft Dining",
    description: "Dining area featuring bold red chairs and exposed brick accents.",
    url: "/images/Posse/Loft.jpg",
    tags: ["Interior", "Residential"],
  },

  {
    title: "Wave Mural Corner",
    description: "Classic armchair paired with a dramatic ocean wave wall mural.",
    url: "/images/Posse/Render_sillon_mural_olas.jpg",
    tags: ["Interior", "Residential"],
  },
  {
    title: "Bathroom with Panoramic View",
    description: "Minimalist bathroom with freestanding tub and lake view.",
    url: "/images/Posse/Baño_ventanal.jpg",
    tags: ["Interior", "Residential"],
  },
  {
    title: "Gobina House Exterior",
    description: "Contemporary residential facade with double-height glazing.",
    url: "/images/Posse/Casa_Gobina.jpg",
    tags: ["Exterior", "Residential"],
  },
  {
    title: "Gobina House Kitchen",
    description: "Minimal kitchen design with natural lighting and warm finishes.",
    url: "/images/Posse/Cocina_Gobina.jpg",
    tags: ["Interior", "Residential"],
  },
  {
    title: "Rural Modern House",
    description:"Contemporary residence landscape.",
    url: "/projects/Noiseless/noiseless_02.jpg",
    tags: ["Exterior", "Residential"],
  },
  {
    title: "Villa",
    description:"Terraces and garden.",
    url: "/projects/Noiseless/noiseless_06.jpg",
    tags: ["Exterior"],
  },
];